vich_uploader:
    db_driver: orm

    mappings:
        productors_directory:
            uri_prefix: /img/producteurs
            upload_destination: '%kernel.project_dir%/public/img/producteurs'
        contracts_directory:
            uri_prefix: /doc/contrats
            upload_destination: '%kernel.project_dir%/public/doc/contrats'
        gallery_directory:
            uri_prefix: /img/gallery
            upload_destination: '%kernel.project_dir%/public/img/gallery'
        articles_directory:
            uri_prefix: /img/articles
            upload_destination: '%kernel.project_dir%/public/img/articles'
